# Generated by Django 2.2.1 on 2019-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='query',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='headers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='params',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
